AWSTemplateFormatVersion: '2010-09-09'
Description: Creates S3 bucket to store Lambda deployment zip (function.zip)

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lambdas-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LambdaCodeBucketName:
    Value: !Ref LambdaCodeBucket