AWSTemplateFormatVersion: '2010-09-09'
Description: Create image resizer Lambda (from S3 zip) + configure S3 event notification (original/ -> Lambda)

Resources:
  ImageResizerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: image-resizer-100x100
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: arn:aws:iam::344077251643:role/LabRole
      Timeout: 20
      MemorySize: 256
      Architectures:
        - x86_64
      Code:
        S3Bucket: !Sub "lambdas-${AWS::AccountId}-${AWS::Region}"
        S3Key: function.zip

  LambdaInvokePermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageResizerLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::images-${AWS::AccountId}-${AWS::Region}"

  # Custom resource Lambda to set bucket notification on an existing bucket
  BucketNotificationSetter:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: set-s3-notification-image-resizer
      Runtime: python3.11
      Handler: index.handler
      Role: arn:aws:iam::344077251643:role/LabRole
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib3
          import os

          s3 = boto3.client("s3")
          http = urllib3.PoolManager()

          def respond(event, context, status, data=None, reason=""):
              body = {
                  "Status": status,
                  "Reason": reason or "OK",
                  "PhysicalResourceId": event.get("PhysicalResourceId", context.log_stream_name),
                  "StackId": event["StackId"],
                  "RequestId": event["RequestId"],
                  "LogicalResourceId": event["LogicalResourceId"],
                  "Data": data or {},
              }
              encoded = json.dumps(body).encode("utf-8")
              http.request(
                  "PUT",
                  event["ResponseURL"],
                  body=encoded,
                  headers={"content-type": "", "content-length": str(len(encoded))},
              )

          def handler(event, context):
              try:
                  props = event["ResourceProperties"]
                  bucket = props["BucketName"]
                  lambda_arn = props["LambdaArn"]

                  cfg = s3.get_bucket_notification_configuration(Bucket=bucket)
                  new_cfg = {
                      "TopicConfigurations": cfg.get("TopicConfigurations", []),
                      "QueueConfigurations": cfg.get("QueueConfigurations", []),
                      "LambdaFunctionConfigurations": cfg.get("LambdaFunctionConfigurations", []),
                  }

                  # Remove existing entry for same lambda to avoid duplicates
                  new_cfg["LambdaFunctionConfigurations"] = [
                      c for c in new_cfg["LambdaFunctionConfigurations"]
                      if c.get("LambdaFunctionArn") != lambda_arn
                  ]

                  req_type = event["RequestType"]
                  if req_type in ("Create", "Update"):
                      new_cfg["LambdaFunctionConfigurations"].append({
                          "LambdaFunctionArn": lambda_arn,
                          "Events": ["s3:ObjectCreated:*"],
                          "Filter": {
                              "Key": {
                                  "FilterRules": [
                                      {"Name": "prefix", "Value": "original/"}
                                  ]
                              }
                          }
                      })
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket,
                          NotificationConfiguration=new_cfg
                      )
                      respond(event, context, "SUCCESS", {"Bucket": bucket})
                      return

                  if req_type == "Delete":
                      # Best effort: just remove our lambda config and keep others
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket,
                          NotificationConfiguration=new_cfg
                      )
                      respond(event, context, "SUCCESS", {"Deleted": True})
                      return

                  respond(event, context, "FAILED", reason=f"Unknown RequestType: {req_type}")

              except Exception as e:
                  respond(event, context, "FAILED", reason=str(e))

  ConfigureImagesBucketNotification:
    Type: Custom::S3BucketNotification
    DependsOn:
      - ImageResizerLambda
      - LambdaInvokePermissionForS3
      - BucketNotificationSetter
    Properties:
      ServiceToken: !GetAtt BucketNotificationSetter.Arn
      BucketName: !Sub "images-${AWS::AccountId}-${AWS::Region}"
      LambdaArn: !GetAtt ImageResizerLambda.Arn

Outputs:
  LambdaName:
    Value: !Ref ImageResizerLambda
  ImagesBucketName:
    Value: !Sub "images-${AWS::AccountId}-${AWS::Region}"
  LambdaCodeBucketName:
    Value: !Sub "lambdas-${AWS::AccountId}-${AWS::Region}"